### ISSUE TITLE
Can I get some advice regarding this error?

### ISSUE THREAD

**Issue by IamSomak** [emolch/bogota-playground#1]
I have been trying my hand out at the rapindinv code recently, but am stuck with a situation. Whenever I try to run the rapidinv code on my data, I am getting the following error. Can I get some suggestion on this?

-------------------------------------------------------------------------------------------------
Initializing
Read input file, check and prepare inversion parameters
Prepare inversion directory, choose stations, prepare data
Taper applied
copied data from data/20171206/prepared
radius 0 set to  1000.0
Calling minimizer result/20171206/minimizer.inp.dist
1 result/20171206/minimizer.inp.dist result/20171206/minimizer.out.dist
2 minimizer < result/20171206/minimizer.inp.dist > result/20171206/minimizer.out.dist
Taper applied
Double couple source inversion (freq domain) - step 1
Inversion step 1
Step 1: Rapid mode activated
Calling minimizer result/20171206/minimizer.inp1-run1
1 result/20171206/minimizer.inp1-run1 result/20171206/minimizer.out1-run1
2 minimizer < result/20171206/minimizer.inp1-run1 > result/20171206/minimizer.out1-run1
minimizer(warn): gfdb: gfdb_get_trace(): invalid request: out of bounds: (1034,10,6)
minimizer(warn): gfdb: gfdb_get_trace(): invalid request: out of bounds: (1034,11,6)
minimizer(warn): gfdb: gfdb_get_trace(): invalid request: out of bounds: (1035,10,6)
minimizer(warn): gfdb: gfdb_get_trace(): invalid request: out of bounds: (1035,11,6)
minimizer(warn): gfdb: gfdb_get_trace(): invalid request: out of bounds: (1034,10,6)
minimizer(warn): gfdb: gfdb_get_trace(): invalid request: out of bounds: (1034,11,6)
minimizer(warn): gfdb: gfdb_get_trace(): invalid request: out of bounds: (1035,10,6)
minimizer(warn): gfdb: gfdb_get_trace(): invalid request: out of bounds: (1035,11,6)
minimizer(warn): gfdb: gfdb_get_trace(): invalid request: out of bounds: (1034,10,6)
minimizer(warn): gfdb: gfdb_get_trace(): invalid request: out of bounds: (1034,11,6)
minimizer(warn): gfdb: gfdb_get_trace(): invalid request: out of bounds: (1035,10,6)
minimizer(warn): gfdb: gfdb_get_trace(): invalid request: out of bounds: (1035,11,6)

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7FD6B9DCA777
#1  0x7FD6B9DCAD7E
#2  0x7FD6B971CCAF
#3  0x446471 in __seismogram_MOD_make_seismogram
#4  0x428AAA in __minimizer_engine_MOD_update_syn_probes at minimizer_engine.f90:?
#5  0x428C1F in __minimizer_engine_MOD_update_misfits at minimizer_engine.f90:?
#6  0x42ACAE in __minimizer_engine_MOD_minimize_lm
#7  0x405B50 in __minimizer_wrappers_MOD_do_minimize_lm
#8  0x40BF49 in MAIN__ at minimizer.f90:?
Segmentation fault (core dumped)
Analysing results inversion step 1...
10 0
ERROR 1: n start sol <> n point sol (minimizer.out)

**Comment by moscardo** [comment]
Hi
I think the error comes from the fact that each starting configuration of Rapidinv
leads to a solution which is outside the GFDB bounds (e.g. sources too
shallow, or too deep, or stations to far...), so that synthetic seismograms cannot be generated

Possible reasons could be:
(1) stations have all epicentral distances too far, compared to the GFDB extent
(2) wrong starting depth, or depth boundaries
(3) wrong amplitude of one or more traces
....

There may be different reasons for this. I cannot provide more suggestions how to fix the specific problem, without having more information on data.

You can contact me at simone.cesca@gfz-potsdam.de providing further details of
your data and inversion setup.
